name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.x environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify '3.8', '3.9', etc., if you need a specific version

      # Install dependencies (if applicable)
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Run your training script
      - name: Run the training script
        run: python3 train.py

